-- MySQL Script generated by MySQL Workbench
-- Tue May 14 07:59:36 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Fallasuniforme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fallasuniforme` (
  `IdFallasuniforme` INT NOT NULL,
  `Fecha` VARCHAR(255) NOT NULL,
  `Materia` VARCHAR(45) NULL,
  PRIMARY KEY (`IdFallasuniforme`));


-- -----------------------------------------------------
-- Table `mydb`.`Noasistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Noasistencia` (
  `IdNoasistencias` INT NOT NULL,
  `Fecha` VARCHAR(255) NOT NULL,
  `Materia` VARCHAR(45) NULL,
  PRIMARY KEY (`IdNoasistencias`));


-- -----------------------------------------------------
-- Table `mydb`.`Evasiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Evasiones` (
  `IdEvasiones` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `Materia` VARCHAR(45) NULL,
  PRIMARY KEY (`IdEvasiones`));


-- -----------------------------------------------------
-- Table `mydb`.`Retardos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Retardos` (
  `IdRetardos` INT NOT NULL,
  `Fecha` VARCHAR(255) NOT NULL,
  `Materia` VARCHAR(45) NULL,
  PRIMARY KEY (`IdRetardos`));


-- -----------------------------------------------------
-- Table `mydb`.`Estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estudiante` (
  `Id_Estudiante` INT NOT NULL,
  `Nombre` VARCHAR(255) NOT NULL,
  `Apellido` VARCHAR(45) NULL,
  `Fallasuniforme_IdFallasuniforme` INT NOT NULL,
  `Noasistencia_IdNoasistencias` INT NOT NULL,
  `Evasiones_IdEvasiones` INT NOT NULL,
  `Retardos_IdRetardos` INT NOT NULL,
  PRIMARY KEY (`Id_Estudiante`, `Fallasuniforme_IdFallasuniforme`, `Noasistencia_IdNoasistencias`, `Evasiones_IdEvasiones`, `Retardos_IdRetardos`),
  INDEX `fk_Estudiante_Fallasuniforme1_idx` (`Fallasuniforme_IdFallasuniforme` ASC) VISIBLE,
  INDEX `fk_Estudiante_Noasistencia1_idx` (`Noasistencia_IdNoasistencias` ASC) VISIBLE,
  INDEX `fk_Estudiante_Evasiones1_idx` (`Evasiones_IdEvasiones` ASC) VISIBLE,
  INDEX `fk_Estudiante_Retardos1_idx` (`Retardos_IdRetardos` ASC) VISIBLE,
  CONSTRAINT `fk_Estudiante_Fallasuniforme1`
    FOREIGN KEY (`Fallasuniforme_IdFallasuniforme`)
    REFERENCES `mydb`.`Fallasuniforme` (`IdFallasuniforme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiante_Noasistencia1`
    FOREIGN KEY (`Noasistencia_IdNoasistencias`)
    REFERENCES `mydb`.`Noasistencia` (`IdNoasistencias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiante_Evasiones1`
    FOREIGN KEY (`Evasiones_IdEvasiones`)
    REFERENCES `mydb`.`Evasiones` (`IdEvasiones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiante_Retardos1`
    FOREIGN KEY (`Retardos_IdRetardos`)
    REFERENCES `mydb`.`Retardos` (`IdRetardos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Colegio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Colegio` (
  `Id_Colegio` INT NOT NULL,
  `Nombre` VARCHAR(255) NOT NULL,
  `Teléfono` VARCHAR(45) NULL,
  `Dirección` VARCHAR(45) NULL,
  `Estudiante_Id_Estudiante` INT NOT NULL,
  PRIMARY KEY (`Id_Colegio`, `Estudiante_Id_Estudiante`),
  INDEX `fk_Colegio_Estudiante_idx` (`Estudiante_Id_Estudiante` ASC) VISIBLE,
  CONSTRAINT `fk_Colegio_Estudiante`
    FOREIGN KEY (`Estudiante_Id_Estudiante`)
    REFERENCES `mydb`.`Estudiante` (`Id_Estudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`DILE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DILE` (
  `Id_DILE` INT NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `Teléfono` INT NULL,
  `Dirección` VARCHAR(45) NULL,
  `Colegio_Id_Colegio` INT NOT NULL,
  `Colegio_Estudiante_Id_Estudiante` INT NOT NULL,
  PRIMARY KEY (`Id_DILE`, `Colegio_Id_Colegio`, `Colegio_Estudiante_Id_Estudiante`),
  INDEX `fk_DILE_Colegio1_idx` (`Colegio_Id_Colegio` ASC, `Colegio_Estudiante_Id_Estudiante` ASC) VISIBLE,
  CONSTRAINT `fk_DILE_Colegio1`
    FOREIGN KEY (`Colegio_Id_Colegio` , `Colegio_Estudiante_Id_Estudiante`)
    REFERENCES `mydb`.`Colegio` (`Id_Colegio` , `Estudiante_Id_Estudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Acudiente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Acudiente` (
  `IdAcudiente` INT NOT NULL,
  `Nombre` VARCHAR(255) NOT NULL,
  `Apellido` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`IdAcudiente`));


-- -----------------------------------------------------
-- Table `mydb`.`Estudiante_has_Acudiente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estudiante_has_Acudiente` (
  `Estudiante_Id_Estudiante` INT NOT NULL,
  `Estudiante_Fallasuniforme_IdFallasuniforme` INT NOT NULL,
  `Estudiante_Noasistencia_IdNoasistencias` INT NOT NULL,
  `Estudiante_Evasiones_IdEvasiones` INT NOT NULL,
  `Estudiante_Retardos_IdRetardos` INT NOT NULL,
  `Acudiente_IdAcudiente` INT NOT NULL,
  PRIMARY KEY (`Estudiante_Id_Estudiante`, `Estudiante_Fallasuniforme_IdFallasuniforme`, `Estudiante_Noasistencia_IdNoasistencias`, `Estudiante_Evasiones_IdEvasiones`, `Estudiante_Retardos_IdRetardos`, `Acudiente_IdAcudiente`),
  INDEX `fk_Estudiante_has_Acudiente_Acudiente1_idx` (`Acudiente_IdAcudiente` ASC) VISIBLE,
  INDEX `fk_Estudiante_has_Acudiente_Estudiante1_idx` (`Estudiante_Id_Estudiante` ASC, `Estudiante_Fallasuniforme_IdFallasuniforme` ASC, `Estudiante_Noasistencia_IdNoasistencias` ASC, `Estudiante_Evasiones_IdEvasiones` ASC, `Estudiante_Retardos_IdRetardos` ASC) VISIBLE,
  CONSTRAINT `fk_Estudiante_has_Acudiente_Estudiante1`
    FOREIGN KEY (`Estudiante_Id_Estudiante` , `Estudiante_Fallasuniforme_IdFallasuniforme` , `Estudiante_Noasistencia_IdNoasistencias` , `Estudiante_Evasiones_IdEvasiones` , `Estudiante_Retardos_IdRetardos`)
    REFERENCES `mydb`.`Estudiante` (`Id_Estudiante` , `Fallasuniforme_IdFallasuniforme` , `Noasistencia_IdNoasistencias` , `Evasiones_IdEvasiones` , `Retardos_IdRetardos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiante_has_Acudiente_Acudiente1`
    FOREIGN KEY (`Acudiente_IdAcudiente`)
    REFERENCES `mydb`.`Acudiente` (`IdAcudiente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Docente` (
  `Id_Docente` INT NOT NULL,
  `Nombre` VARCHAR(255) NOT NULL,
  `Apellido` VARCHAR(45) NULL,
  `Materia` VARCHAR(45) NULL,
  PRIMARY KEY (`Id_Docente`));


-- -----------------------------------------------------
-- Table `mydb`.`Estudiante_has_Docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estudiante_has_Docente` (
  `Estudiante_Id_Estudiante` INT NOT NULL,
  `Estudiante_Fallasuniforme_IdFallasuniforme` INT NOT NULL,
  `Estudiante_Noasistencia_IdNoasistencias` INT NOT NULL,
  `Estudiante_Evasiones_IdEvasiones` INT NOT NULL,
  `Estudiante_Retardos_IdRetardos` INT NOT NULL,
  `Docente_Id_Docente` INT NOT NULL,
  PRIMARY KEY (`Estudiante_Id_Estudiante`, `Estudiante_Fallasuniforme_IdFallasuniforme`, `Estudiante_Noasistencia_IdNoasistencias`, `Estudiante_Evasiones_IdEvasiones`, `Estudiante_Retardos_IdRetardos`, `Docente_Id_Docente`),
  INDEX `fk_Estudiante_has_Docente_Docente1_idx` (`Docente_Id_Docente` ASC) VISIBLE,
  INDEX `fk_Estudiante_has_Docente_Estudiante1_idx` (`Estudiante_Id_Estudiante` ASC, `Estudiante_Fallasuniforme_IdFallasuniforme` ASC, `Estudiante_Noasistencia_IdNoasistencias` ASC, `Estudiante_Evasiones_IdEvasiones` ASC, `Estudiante_Retardos_IdRetardos` ASC) VISIBLE,
  CONSTRAINT `fk_Estudiante_has_Docente_Estudiante1`
    FOREIGN KEY (`Estudiante_Id_Estudiante` , `Estudiante_Fallasuniforme_IdFallasuniforme` , `Estudiante_Noasistencia_IdNoasistencias` , `Estudiante_Evasiones_IdEvasiones` , `Estudiante_Retardos_IdRetardos`)
    REFERENCES `mydb`.`Estudiante` (`Id_Estudiante` , `Fallasuniforme_IdFallasuniforme` , `Noasistencia_IdNoasistencias` , `Evasiones_IdEvasiones` , `Retardos_IdRetardos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiante_has_Docente_Docente1`
    FOREIGN KEY (`Docente_Id_Docente`)
    REFERENCES `mydb`.`Docente` (`Id_Docente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
